USERNAME = "//input[@id='user-name']"
PASSWORD = "//input[@id='password']"
LOGIN = "//input[@id='login-button']"
PRODUCT_DETAILS = "//div[normalize-space()="
ADD_CART = "//button[@id='add-to-cart-sauce-labs-bike-light']"
SHOPPING_CART = "//a[@class='shopping_cart_link']"
CHECKOUT_BUTTON = "//button[@id='checkout']"
FIRSTNAME = "//input[@id='first-name']"
LASTNAME = "//input[@id='last-name']"
PINCODE =  "//input[@id='postal-code']"
CONTINUE_BUTTON = "//input[@id='continue']"
FINISH_PURCHASE = "//button[@name='finish']"
ORDER_PLACED = "//h2[normalize-space()='Thank you for your order!']"
PATH = "/Users/singhkushagra/PycharmProjects/seleniumAutomatinProject/screenshot/"
RES = PATH + "failure.png"